twig:
    default_path: '%kernel.project_dir%/templates'

    # Des variable disponible dans tous les fichiers twig
    globals:
        cartService: "@App\\Cart\\CartService"
    
    form_themes: [ 'bootstrap_4_layout.html.twig' ]

when@test:
    twig:
        strict_variables: true
